# Generated by Django 4.1.2 on 2022-10-05 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Working', 'Working')], max_length=25),
        ),
    ]
